ManageYourBudget/WebApp/Controllers/StatisticPageController.cs
using System.Security.Claims;
using System.Text;
using Application.DTOs.StatisticDTO;
using Application.Interfaces;
using Microsoft.AspNetCore.Mvc;
using WebApp.Models;
using Application.Utils;

namespace WebApp.Controllers
{
    public class StatisticPageController : Controller
    {
        private readonly IStatisticService _statisticService;
        private readonly IExportDataService _exportDataService;
        private readonly IHttpContextAccessor _httpContextAccessor;
        private readonly ISettingsService _settingsService;

        public StatisticPageController(IStatisticService statisticService, IHttpContextAccessor httpContextAccessor, ISettingsService settingsService, IExportDataService exportDataService)
        {
            _statisticService = statisticService;
            _httpContextAccessor = httpContextAccessor;
            _settingsService = settingsService;
            _exportDataService = exportDataService;
        }

        //public enum ExportFormat
        //{
        //    CSV,
        //    XML,
        //    XLSX
        //}

        public async Task<IActionResult> Index()
        {
            string userId = _httpContextAccessor.HttpContext.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;

            var temp = await _settingsService.GetUserSettingsAsync(userId);
            bool isLightTheme = temp.IsLightTheme;
            ViewBag.Theme = isLightTheme ? "Light" : "Dark";

            //string aspNetCoreCookiesValue = _httpContextAccessor.HttpContext.Request.Cookies[".AspNetCore.Cookies"];

            try
            {
                var defaultStatistics = await _statisticService.GetAllData(DateTime.Now.AddMonths(-1), DateTime.Now, userId);

                List<StatisticViewModel> statistics = new List<StatisticViewModel>();

                for (int i = 0; i < defaultStatistics?.ExpensesStatistics?.Count; i++)
                {
                    var income = defaultStatistics?.IncomeStatistics?[i] ?? new IncomeStatisticDTO();
                    var expense = defaultStatistics?.ExpensesStatistics?[i] ?? new TotalExpensesDTO();
                    var saving = defaultStatistics?.SavingsStatistics?[i] ?? new SavedStatisticDTO();

                    var model = new StatisticViewModel
                    {
                        Incomes = income.TotalAmount,
                        SummaryExpenses = expense.TotalAmount,
                        Savings = saving.TotalAmount,
                        Date = income.Month,
                    };

                    statistics.Add(model);
                }

                return View("~/Views/StatisticPage/Index.cshtml", statistics);
            }
            catch (Exception ex)
            {
                return StatusCode(500, "Failed to retrieve default statistics.");
            }
        }

        [HttpGet]
        public async Task<IActionResult> GetStatistics(DateTime startDate, DateTime endDate, string category)
        {
            try
            {
                string userId = _httpContextAccessor.HttpContext.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
                var statistics = await _statisticService.GetAllData(startDate, endDate, userId);

                List<StatisticViewModel> viewModelList = new List<StatisticViewModel>();

                for (int i = 0; i < statistics?.ExpensesStatistics?.Count; i++)
                {
                    var income = statistics?.IncomeStatistics?[i] ?? new IncomeStatisticDTO();
                    var expense = statistics?.ExpensesStatistics?[i] ?? new TotalExpensesDTO();
                    var saving = statistics?.SavingsStatistics?[i] ?? new SavedStatisticDTO();

                    var model = new StatisticViewModel
                    {
                        Incomes = income.TotalAmount,
                        SummaryExpenses = expense.TotalAmount,
                        Savings = saving.TotalAmount,
                        Date = income.Month,
                    };

                    viewModelList.Add(model);
                }

                return View("~/Views/StatisticPage/Index.cshtml", viewModelList); // Pass view models to the view
            }
            catch (Exception ex)
            {
                return StatusCode(500, $"Failed to retrieve statistics: {ex.Message}");
            }
        }

        [HttpGet]
        public async Task<IActionResult> ExportStatistics(DateTime startDate, DateTime endDate, ExportFormat format)
        {
            string userId = _httpContextAccessor.HttpContext.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            var result = await _exportDataService.ExportData(startDate, endDate, userId, format);

            if (!result.Success)
                return StatusCode(500, "Failed to export data.");

            return File(result.FileContents, result.ContentType, result.FileName);
        }
    }
}

ManageYourBudget/WebApp/Views/StatisticPage/Index.cshtml
@{
    ViewData["Title"] = "Statistic";
}
@model IEnumerable<StatisticViewModel>
<head>
    <meta charset="utf-8" />
    <title>Statistic</title>
    <meta content="width=device-width, initial-scale=1" name="viewport">
    <link rel="stylesheet" href="~/css/Statistic.css">
</head>
<body >
    <div class="section">
        <div class="container">
            <div class="statistic">
                <div class="statistic-manipulation">
                    <div class="form-group">
                        <label class="statistic-text" for="startDate">Start Date:</label>
                        <input class="statistic-text form-control" type="date" id="startDate" name="startDate" />
                    </div>
                    <div class="form-group">
                        <label class="statistic-text" for="endDate">End Date:</label>
                        <input class="statistic-text form-control" type="date" id="endDate" name="endDate" />
                    </div>

                    <div class="button-grid">
                        <div class="custom-button-wrapper">
                            <a id="getStatistics" class="custom-btn" href="@Url.Action("GetStatistics", "StatisticPage", new { startDate=DateTime.Today.AddMonths(-1), endDate=DateTime.Today, format="CSV" })">Show statistic</a>
                        </div>
                        <div class="custom-button-wrapper">
                            <a id="exportCsvLink" class="custom-btn" href="@Url.Action("ExportStatistics", "StatisticPage", new { startDate = DateTime.Today.AddMonths(-1), endDate = DateTime.Today, format = "CSV" })">Export CSV</a>
                        </div>
                        <div class="custom-button-wrapper">
                            <a id="exportXmlLink" class="custom-btn" href="@Url.Action("ExportStatistics", "StatisticPage", new { startDate = DateTime.Today.AddMonths(-1), endDate = DateTime.Today, format = "XML" })">Export XML</a>
                        </div>
                        <div class="custom-button-wrapper">
                            <a id="exportXlsxLink" class="custom-btn" href="@Url.Action("ExportStatistics", "StatisticPage", new { startDate = DateTime.Today.AddMonths(-1), endDate = DateTime.Today, format = "XLSX" })">Export XLSX</a>
                        </div>
                    </div>

                </div>

                <div class="table">
                    <table id="statisticsTable">
                        <thead>
                            <tr>
                                <th>Income</th>
                                <th>Summary Expenses</th>
                                <th>Saved</th>
                                <th>Month</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var statistic in Model)
                            {
                                <tr>
                                    <td>@statistic.Incomes</td>
                                    <td>@statistic.SummaryExpenses</td>
                                    <td>@statistic.Savings</td>
                                    <td>@statistic.Date.ToString("MMMM, yyyy")</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    
    <script>
       
        var startDateInput = document.getElementById('startDate');
        var endDateInput = document.getElementById('endDate');

        // Функція для збереження значень полів дати в localStorage
        function saveInputValues() {
            localStorage.setItem('startDateValue', startDateInput.value);
            localStorage.setItem('endDateValue', endDateInput.value);
        }

        // Додавання обробника подій change для полів дати
        startDateInput.addEventListener('change', saveInputValues);
        endDateInput.addEventListener('change', saveInputValues);

        // Функція для відновлення збережених значень полів дати з localStorage
        function restoreInputValues() {
            var savedStartDate = localStorage.getItem('startDateValue');
            var savedEndDate = localStorage.getItem('endDateValue');
            if (savedStartDate && savedEndDate) {
                startDateInput.value = savedStartDate;
                endDateInput.value = savedEndDate;
            }
        }

        // Перевірка, чи передані значення полів дати через запит
        function checkQueryParameters() {
            const urlParams = new URLSearchParams(window.location.search);
            const startDateParam = urlParams.get('startDate');
            const endDateParam = urlParams.get('endDate');

            // Якщо значення не передані через запит, очищаємо поля дати
            if (!startDateParam || !endDateParam) {
                startDateInput.value = '';
                endDateInput.value = '';
            }
        }

        // Викликаємо функції відновлення та перевірки запиту при завантаженні сторінки
        restoreInputValues();
        checkQueryParameters();
        function updateExportLinks() {
            var startDate = document.getElementById('startDate').value;
            var endDate = document.getElementById('endDate').value;
            var baseUrl = '@Url.Action("ExportStatistics", "StatisticPage")';

            document.getElementById('exportCsvLink').href = `${baseUrl}?startDate=${startDate}&endDate=${endDate}&format=CSV`;
            document.getElementById('exportXmlLink').href = `${baseUrl}?startDate=${startDate}&endDate=${endDate}&format=XML`;
            document.getElementById('exportXlsxLink').href = `${baseUrl}?startDate=${startDate}&endDate=${endDate}&format=XLSX`;

            document.getElementById('getStatistics').href = `@Url.Action("GetStatistics", "StatisticPage")?startDate=${startDate}&endDate=${endDate}`;
        }

        document.getElementById('startDate').addEventListener('change', updateExportLinks);
        document.getElementById('endDate').addEventListener('change', updateExportLinks);

        // Call updateExportLinks to set initial values correctly
        updateExportLinks();
    </script>
</body>